"""initial tables

Revision ID: cb5712b65b39
Revises: 
Create Date: 2026-07-13 20:34:36.107787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb5712b65b39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('emoji', sa.String(length=10, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('word', sa.String(length=100), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language', 'emoji', 'word', name='uq_answer')
    )
    with op.batch_alter_table('answer_counts', schema=None) as batch_op:
        batch_op.create_index('idx_lang_emoji', ['language', 'emoji'], unique=False)

    op.create_table('rooms',
    sa.Column('id', sa.String(length=4), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('current_emoji', sa.String(length=10, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(length=4), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(length=4), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('emoji', sa.String(length=10, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('guess', sa.String(length=100), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissions')
    op.drop_table('players')
    op.drop_table('rooms')
    with op.batch_alter_table('answer_counts', schema=None) as batch_op:
        batch_op.drop_index('idx_lang_emoji')

    op.drop_table('answer_counts')
    # ### end Alembic commands ###
